### ISSUE TITLE
My RTSP link not working with your code

### ISSUE THREAD

**Issue by mariummalik22** [Streamedian/html5_rtsp_player#2]
My RTSP link works well with VLC player and vlc plugin on firefox but does not work when I am replacing the link in your code with mine.

**Comment by victorgrenke** [comment]
Hello

I think your rtsp source is working fine inside your internal network (like 192.168.xx.xx), therefore VLC plays it.
When you add your rtsp link to our proxy server (over test page) it cannot get stream from you because proxy is not in your private network. As soon as you redirect your stream to the global network our server will be able to get it and will redirect to the player.

**Comment by ProudNoob** [comment]
hi the same problem
i change by link as you guide rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4
but still not working ..........
any help

**Comment by victorgrenke** [comment]
hello

Try to install our websocket proxy on your PC and check your stream with 
it. Probably our proxy server was not available when you tested your 
stream.
Also we have checked your stream with our proxy server and in your 
stream there are b-frames but our player is not processing it so you 
will see stream anyway but with some green artifacts.

Regards
Victor

21.05.2016 11:16, ProudNoob пишет:
