### ISSUE TITLE
Player always mute, no sound

### ISSUE THREAD

**Issue by ucomdemo** [Streamedian/html5_rtsp_player#8]
I follow your step to setup test environment,and test.boundle.js file.
I create html5 file and use the following url for test.
rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov
It works, player can play the video, but the player always mute, I can't hear any sound,any suggestion?

**Comment by victorgrenke** [comment]
Hello

Player supports MP4A-LATM  for now.

In your stream format is  AAC-hbr  - player that I put on github don't 
support it.



29.07.2016 9:51, ucomdemo пишет:

**Comment by ucomdemo** [comment]
Any further plan to support other type of audio, like AAC-hbr ? or do you hava a paid version can support it?

**Comment by victorgrenke** [comment]
1. RTP-payload for audio mpeg4-generic (AAC-hbr / AAC-lbr) has been supported in new version.
It will be posted on GitHub as soon as all current problems with proxy infrastructure will be solved, 
because new version works with proxy, backward incompatible that now is in repository.
2. Authorization of flows (to proxy side and player) is also supported in new version and will be available after publication.

**Comment by Praneeth8080** [comment]
Hi,
Even I face the same problem on my end. There is no audio only video.
Could you mention the supported payloads for audio in the new version? And also when the new version will be available.
