### ISSUE TITLE
Use Node.js proxy server wrong.(Windows10)

### ISSUE THREAD

**Issue by gtk2k** [Streamedian/html5_rtsp_player#80]
Use for IP Camera.
streamedian.js v1.8 (from https://streamedian.com/)
wss://specforge.com/ws/ and Wndows websock_rtsp_proxy work.
[websock_rtsp_proxy.log](https://github.com/Streamedian/html5_rtsp_player/files/1863489/websock_rtsp_proxy.log)
(privacy pixelated)
![html5_rtsp_player_websock_rtsp_proxy](https://user-images.githubusercontent.com/309829/38136691-30b8cb18-345b-11e8-9321-784e658a6267.png)

but, server.js run on Node.js wrong.
[nodejs_serverjs.log](https://github.com/Streamedian/html5_rtsp_player/files/1863490/nodejs_serverjs.log) 
(Image not modified)
![html5_rtsp_player_serverjs](https://user-images.githubusercontent.com/309829/38136710-490a4944-345b-11e8-88f7-846aa64cf6de.png)

**Comment by kreopt** [comment]
We have not support node.js server. It just merged pull request for tests
and may not respond to all requirements

30 мар. 2018 г. 18:51 пользователь "gtk2k" <notifications@github.com>
написал:

Use for IP Camera.
streamedian.js v1.8 (from https://streamedian.com/)
wss://specforge.com/ws/ and Wndows websock_rtsp_proxy work.
websock_rtsp_proxy.log
<https://github.com/Streamedian/html5_rtsp_player/files/1863489/websock_rtsp_proxy.log>
(privacy pixelated)
[image: html5_rtsp_player_websock_rtsp_proxy]
<https://user-images.githubusercontent.com/309829/38136691-30b8cb18-345b-11e8-9321-784e658a6267.png>

but, server.js run on Node.js wrong.
nodejs_serverjs.log
<https://github.com/Streamedian/html5_rtsp_player/files/1863490/nodejs_serverjs.log>
(Image not modified)
[image: html5_rtsp_player_serverjs]
<https://user-images.githubusercontent.com/309829/38136710-490a4944-345b-11e8-88f7-846aa64cf6de.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Streamedian/html5_rtsp_player/issues/80>, or mute the
thread

**Comment by gtk2k** [comment]
Oh, OK.
